# Generated by Django 3.2.8 on 2021-11-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
