# Generated by Django 3.2.8 on 2022-01-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='ilyas', on_delete=django.db.models.deletion.CASCADE, to='questions.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=19990101),
        ),
    ]
